import {
  FaUserMd,
  FaCalendarCheck,
  FaEnvelope,
  FaPhone,
  FaHospital,
  FaUsers,
  FaPlus,
  FaTrash,
  FaEdit,
  FaSearch,
  FaSignOutAlt,
  FaClipboardList,
  FaClock,
  FaCheckCircle,
  FaTimesCircle,
  FaLock,
  FaUser,
  FaPills,
  FaStethoscope,
  FaAmbulance,
  FaFlask,
  FaMobileAlt,
  FaStar,
  FaMapMarkerAlt,
  FaInfoCircle,
  FaExclamationTriangle,
  FaPlug,
  FaHeart,
  FaBrain,
  FaBone,
  FaBaby,
  FaEye,
  FaTooth,
  FaComments,
  FaHourglassHalf,
  FaFlagCheckered,
  FaRocket,
  FaTimes,
} from "react-icons/fa";
import { MdDashboard, MdEmail, MdMessage, MdScience } from "react-icons/md";
import { HiOutlineLogout } from "react-icons/hi";

export {
  FaUserMd,
  FaCalendarCheck,
  FaEnvelope,
  FaPhone,
  FaHospital,
  FaUsers,
  FaPlus,
  FaTrash,
  FaEdit,
  FaSearch,
  FaSignOutAlt,
  FaClipboardList,
  FaClock,
  FaCheckCircle,
  FaTimesCircle,
  FaLock,
  FaUser,
  FaPills,
  FaStethoscope,
  FaAmbulance,
  FaFlask,
  FaMobileAlt,
  FaStar,
  FaMapMarkerAlt,
  FaInfoCircle,
  FaExclamationTriangle,
  FaPlug,
  FaHeart,
  FaBrain,
  FaBone,
  FaBaby,
  FaEye,
  FaTooth,
  FaComments,
  FaHourglassHalf,
  FaFlagCheckered,
  FaRocket,
  FaTimes,
  MdDashboard,
  MdEmail,
  MdMessage,
  MdScience,
  HiOutlineLogout,
};

export const SPEC_ICONS = {
  Cardiology: FaHeart,
  Cardiologist: FaHeart,
  Dermatology: FaUserMd,
  Dermatologist: FaUserMd,
  Neurology: FaBrain,
  Neurologist: FaBrain,
  Orthopedics: FaBone,
  Orthopedic: FaBone,
  Pediatrics: FaBaby,
  Pediatrician: FaBaby,
  Ophthalmology: FaEye,
  Dentistry: FaTooth,
  General: FaUserMd,
  default: FaUserMd,
};

export function SpecIcon({ specialization, size = 22 }) {
  const Icon = SPEC_ICONS[specialization] || SPEC_ICONS.default;
  return <Icon size={size} aria-hidden="true" />;
}
