spring.datasource.url=${DB_URL:jdbc:mysql://localhost:3306/healthcare}

spring.datasource.username=${DB_USERNAME:root}

spring.datasource.password=${DB_PASSWORD:Siddhi@2004}

spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

server.port=${PORT:8080}